quiet: true
skip-check:
  # Our containers are for testing purposes only
  - CKV_DOCKER_2 # "Ensure that HEALTHCHECK instructions have been added to container images"
  - CKV_DOCKER_3 # "Ensure that a user for the container has been created"
