EXTENDS: https://raw.githubusercontent.com/ScribeMD/.github/0.11.4/.github/base.mega-linter.yaml
JAVASCRIPT_ES_CLI_EXECUTABLE: [node, .yarn/releases/yarn-3.6.3.cjs, run, eslint]
# Work around https://github.com/oxsecurity/megalinter/issues/2500.
SPELL_CSPELL_PRE_COMMANDS:
  - command: npm install @cspell/dict-win32@2.0.1
    continue_if_failed: false
TYPESCRIPT_ES_CLI_EXECUTABLE: [node, .yarn/releases/yarn-3.6.3.cjs, run, eslint]
