APPLY_FIXES: all
DEFAULT_BRANCH: main
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FORMATTERS_DISABLE_ERRORS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
CREDENTIALS_SECRETLINT_ARGUMENTS: --secretlintignore .gitignore
JSON_PRETTIER_FILE_EXTENSIONS:
  - .json
  - .md
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yaml
SPELL_CSPELL_CONFIG_FILE: LINTER_DEFAULT
