APPLY_FIXES: all
FILTER_REGEX_EXCLUDE: \.pnp\.(c|loader\.m)js|\.yarn/|dist
DEFAULT_BRANCH: main
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FAIL_IF_UPDATED_SOURCES: true
FORMATTERS_DISABLE_ERRORS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
CREDENTIALS_SECRETLINT_ARGUMENTS: --secretlintignore .gitignore
JAVASCRIPT_DEFAULT_STYLE: prettier
JSON_PRETTIER_FILE_EXTENSIONS:
  - .json
  - .md
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yaml
SPELL_CSPELL_CONFIG_FILE: LINTER_DEFAULT
TYPESCRIPT_DEFAULT_STYLE: prettier
