# Make dependencies available locally, so MegaLinter can run ESLint via Yarn.
enableGlobalCache: false

plugins:
  - checksum: 55d54388ad171beb0a12e808e375d3c5f8632556a2eed7d03b38b8304514b07831ef7a9f9e78410287313940d107ea4634cfa2933e08459a165c432cea55bdba
    path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.13.1/bundles/@yarnpkg/plugin-licenses.js"

supportedArchitectures:
  # The Yarn licenses plugin needs all dependencies installed in order to list
  # their licenses without crashing.
  os:
    - current
    - darwin # for fsevents, a MacOS-only transitive dependency of Jest

# Keep in sync with package.json.
yarnPath: .yarn/releases/yarn-4.0.2.cjs
