name: Docker Cache
author: Kurt von Laven
description: Cache Docker images whether built or pulled.
branding:
  icon: download
  color: blue
inputs:
  key:
    description: >
      The cache key to ferry to the official GitHub cache action. restore-keys
      are not supported, because partial cache restoration leads to a "snowball"
      effect.
    required: true
  read-only:
    description: If "true", disables saving the cache upon cache miss
    required: false
    default: "false"
outputs:
  cache-hit:
    description: >
      The ferried output of the official GitHub cache action. True on cache hit
      (even if the subsequent docker load failed) and false on cache miss.
runs:
  using: node16
  main: dist/main/index.js
  post-if: success()
  post: dist/post/index.js
