version: "0.2"
language: en-US
useGitignore: true
usePnP: true
ignorePaths:
  - .vscode
import:
  - "@cspell/dict-win32/cspell-ext.json"
dictionaryDefinitions:
  - name: custom
    path: .dictionary.txt
dictionaries:
  - custom
  - docker
  - fullstack
  - npm
  - python
  - python-common
  - win32
